[project]
name = "dlt-ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.39.11",
    "dlt[athena]>=1.15.0",
    "pandas>=2.3.2",
    "python-dotenv>=1.1.1",
]
