[destination.filesystem]
bucket_url = "s3://msc-sandbox-iceberg/dlt"

[destination.filesystem.credentials]
aws_access_key_id=""
aws_secret_access_key=""
aws_session_token=""

[destination.athena]
force_iceberg = "True"
query_result_bucket="s3://[results_bucket_name]"

[destination.athena.credentials]
aws_access_key_id=""
aws_secret_access_key=""
region_name=""
database="awsdatacatalog"
